import { Router, type IRouter } from "express";
import healthRouter from "./health";
import blocksRouter from "./blocks";
import apartmentsRouter from "./apartments";
import objectsRouter from "./objects";
import customersRouter from "./customers";
import salesRouter from "./sales";
import installmentsRouter from "./installments";
import rentalsRouter from "./rentals";
import objectPaymentsRouter from "./object_payments";
import communalRouter from "./communal";
import internetRouter from "./internet";
import tariffsRouter from "./tariffs";
import statsRouter from "./stats";
import quartersRouter from "./quarters";
import buildingsRouter from "./buildings";
import authRouter from "./auth";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/quarters", quartersRouter);
router.use("/buildings", buildingsRouter);
router.use("/blocks", blocksRouter);
router.use("/apartments", apartmentsRouter);
router.use("/objects", objectsRouter);
router.use("/customers", customersRouter);
router.use("/sales", salesRouter);
router.use("/installments", installmentsRouter);
router.use("/rentals", rentalsRouter);
router.use("/object-payments", objectPaymentsRouter);
router.use("/communal", communalRouter);
router.use("/internet", internetRouter);
router.use("/tariffs", tariffsRouter);
router.use("/stats", statsRouter);
router.use("/auth", authRouter);
router.use("/admin", adminRouter);

export default router;
